name: Actualizar en VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Conectar al VPS y actualizar
        uses: appleboy/ssh-action@master
        with:
          host: 206.189.238.9
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/html/tuboliteros/
            source venv/bin/activate
            git pull

            pip install -r requirements.txt

            python manage.py migrate

            python manage.py collectstatic
            cp -r ./static/tmp/* ./static/
            rm -R ./static/tmp/

            sudo service apache2 restart
